name: personal_portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_theme_switcher: ^2.0.10
  flutter_animate: ^4.5.2
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  loading_animation_widget: ^1.3.0
  localization: ^2.1.1
  signals: ^5.5.0
  toastification: ^2.3.0
  shared_preferences: ^2.3.2
  gif: ^2.3.0
  url_strategy: ^0.3.0
  flutter_svg: ^2.0.16
  auto_size_text: ^3.0.0
  dio: ^5.7.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  android: false
  ios: false
  web: true
  
  color: "#121414"

  image: assets/native_splash.png

  android_12:
    color: "#121414"
    image: assets/native_splash.png

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo/web.png"
    background_color: "#181C24"
    theme_color: "#181C24"
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/gifs/
    - assets/svgs/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe/SegoeUI-Light.ttf
          weight: 200
        - asset: assets/fonts/Segoe/SegoeUI.ttf
          weight: 400
        - asset: assets/fonts/Segoe/SegoeUI-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Segoe/SegoeUI-Bold.ttf
          weight: 700
          