name: personal_portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_theme_switcher: ^2.0.10
  custom_refresh_indicator: ^4.0.1
  flutter_animate: ^4.5.0
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  loading_animation_widget: ^1.2.1
  localization: ^2.1.1
  signals: ^5.3.0
  toastification: ^2.1.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  gif: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_native_splash:
  android: false
  ios: false
  web: true
  
  color: "#F9F9F9"
  color_dark: "#21262B"

  image: assets/native_splash.png
  image_dark: assets/native_splash.png

  android_12:
    color: "#F9F9F9"
    color_dark: "#21262B"
    image: assets/native_splash.png
    image_dark: assets/native_splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

