name: personal_portifolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_theme_switcher: ^2.0.10
  custom_refresh_indicator: ^4.0.1
  flutter_animate: ^4.5.0
  flutter_vibrate: ^1.3.0
  gap: ^3.0.1
  loading_animation_widget: ^1.2.1
  localization: ^2.1.1
  signals: ^5.3.0
  toastification: ^2.1.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  gif: ^2.3.0
  url_strategy: ^0.3.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_native_splash:
  android: false
  ios: false
  web: true
  
  color: "#121414"

  image: assets/native_splash.png

  android_12:
    color: "#121414"
    image: assets/native_splash.png

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo/web.png"
    background_color: "#181C24"
    theme_color: "#181C24"
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe/SegoeUI-Light.ttf
          weight: 200
        - asset: assets/fonts/Segoe/SegoeUI.ttf
          weight: 400
        - asset: assets/fonts/Segoe/SegoeUI-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Segoe/SegoeUI-Bold.ttf
          weight: 700
          